### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by NitishaS-812k** [arve0/ipynbcompress#3]
I have jupyter notebook to compress, let's call it 'abcd.ipynb'
I entered the following code s described in the README
`from ipynbcompress import compress`
`compress('abcd.ipynb')`
I obtain the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nitisha/.local/lib/python3.8/site-packages/ipynbcompress/ipynbcompress.py", line 44, in compress
    for key in keys:
RuntimeError: dictionary keys changed during iteration
`
I think this issue is only caused in Python3. I haven't checked it for Python2 ( because I'm unable to install any modules for Python2), but it should work for Python3, if we force the dictionary to be a list, as described <a href = "https://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error">here </a>

**Comment by arve0** [comment]
Hi! I'm sorry, but I do not have time to debug your issue. If you find the error, please update me.
