### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython.nbformat'

### ISSUE THREAD

**Issue by yassine-rd** [arve0/ipynbcompress#5]
So I would like to compress a jupyter notebook. Let's call it notebook.ipynb per exemple.
I installed ipynbcompress module using the following command : `pip install ipynbcompress`
However, when i run `ipynb-compress notebook.ipynb`, I get the following error message :

```code
Traceback (most recent call last):
  File "/Users/kheey/miniforge3/envs/tensorflow/bin/ipynb-compress", line 5, in <module>
    from ipynbcompress import compress
  File "/Users/kheey/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ipynbcompress/__init__.py", line 8, in <module>
    from .ipynbcompress import compress
  File "/Users/kheey/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ipynbcompress/ipynbcompress.py", line 6, in <module>
    from IPython.nbformat import read, write
ModuleNotFoundError: No module named 'IPython.nbformat'
```

I'm actually using Python 3.9.13 and I have IPython module 8.5.0 installed on my conda env.
It could be that ipynbcompress is not available on Python 3.9.13 ?

**Comment by SkalskiP** [comment]
Hi 👋🏻! I have the same problem on python `3.9.6` - `ModuleNotFoundError: No module named 'IPython.nbformat'`. any updates?

**Comment by bughht** [comment]
I've also encounter the same problem on python 3.8
